#steps:
#- name: 'gcr.io/cloud-builders/wget'
#  args: ['-O', 'localfile.zip', 'http://www.example.com/remotefile.zip']
steps:
  - name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'https://github.com/odegay/rr-raspberryprocessor.git']
  - name: 'gcr.io/gsutil'
  args: ['gsutil', 'cp', './src/client/robotprocessor.py', 'gs://remote-robot/robotprocessor.py']  